GradExam/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GradExam.Models
{
    public class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Semester { get; set; }
        public string Section { get; set; }
        public string InstructorName { get; set; }
        public Concentration Concentration { get; set; }
    }
}

GradExam/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GradExam.Models;
using GradExam.Services;
using Microsoft.AspNetCore.Mvc;

namespace GradExam.Controllers
{
    public class CourseController : Controller
    {
        private IGradeExamRepository context;

        public CourseController(IGradeExamRepository context)
        {
            this.context = context;
        }

        public IActionResult Delete(int id)
        {
            var course = context.ReadCourse(id);
            if (course == null)
            {
                return RedirectToAction("Index");
            }
            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            context.DeleteCourse(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var course = context.ReadCourse(id);
            if (course == null)
            {
                return RedirectToAction("Index");
            }
            return View(course);
        }

        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Course course)
        {

            if (ModelState.IsValid)
            {
                context.AddCourse(course);
                return RedirectToAction("Index");
            }
            return View(course);

        }
    }
}

GradExam/Views/Course/Add.cshtml
@model GradExam.ViewModels.AddCourseViewModel
@{
    ViewData["Title"] = "Add";
}

<h2>Add</h2>
@using (Html.BeginForm("Add", "Course"))
{
    @Html.ValidationSummary()

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <br>
    <br>

    @Html.LabelFor(model => model.Semester)
    @Html.EditorFor(model => model.Semester)

    <br>
    <br>

    @Html.LabelFor(model => model.Section)
    @Html.EditorFor(model => model.Section)

    <br>
    <br>

    @Html.LabelFor(model => model.InstructorName)
    @Html.EditorFor(model => model.InstructorName)

    <br>
    <br>

    <label>Concentration: </label>
    <select id="myList">
        <option value="1">Applied Computer Science</option>
        <option value="2">Information Technology</option>
    </select>

    <br>
    <br>

    <button type="submit">Submit</button>
}

GradExam/Views/Course/Delete.cshtml
@model GradExam.Models.Course

@{
    ViewData["Title"] = $"Delete Course: {Model.Name}";
}

<h2>@ViewData["Title"]</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Section)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Section)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InstructorName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InstructorName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index" asp-controller="Home">Back to List</a>
    </form>
</div>

GradExam/Views/Course/Details.cshtml
@model GradExam.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Section)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Section)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InstructorName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InstructorName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-controller="Course" asp-route-id="@Model.Id">Edit</a>
    <a asp-action="Index">Back to List</a>
</div>

GradExam/Views/Course/Edit.cshtml
@model GradExam.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Section" class="control-label"></label>
                <input asp-for="Section" class="form-control" />
                <span asp-validation-for="Section" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstructorName" class="control-label"></label>
                <input asp-for="InstructorName" class="form-control" />
                <span asp-validation-for="InstructorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>